server:
  port: 88

spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.181.137:8848
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast   # 路由给renren-fast
          predicates:           # 什么情况下路由给它
            - Path=/api/**      # 默认前端项目都带上api前缀，就是我们前面题的localhost:88/api
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}  # 把/api/* 改变成 /renren-fast/*



